### ISSUE TITLE
Decouple the ClusterQueue snapshots queue from the CQ reconciler

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#1099]
This is a follow up for the comment: https://github.com/kubernetes-sigs/kueue/pull/1069#discussion_r1319096989

**What would you like to be cleaned**:

Decouple the `snaphotsQueue` from the CQ reconciler.

**Why is this needed**:

To improve readability by not overloading the reconciler with responsibilities.

**Comment by mimowo** [comment]
@lowang-bh FYI: https://github.com/kubernetes-sigs/kueue/pull/1135 makes the coupling somewhat stronger. I'm wondering if this is still feasible.

**Comment by mimowo** [comment]
I think it is fair to close it, we probably prefer to have the visibility server anyway, and we could drop the workloads in status entirely in the future releases. It is Alpha level anyway at this point.

**Comment by tenzen-y** [comment]
> we probably prefer to have the visibility server 

I'd also prefer to use the visibility server. However, we can not remove ClusterQueueVisibility without visibility-server since the ClusterQueueVisibility without visibility-server is under the beta stage, and we already expose pending workloads via beta API, ClusterQueue.

So, I think that some refactoring would still be effective.

**Comment by mimowo** [comment]
Hm, even though the feature itself is Alpha-level: https://github.com/kubernetes-sigs/kueue/blob/38cedb172e42cbbeb8c12225baab827583db6c3b/pkg/features/kube_features.go#L40? 

I would prefer to deprecate it and drop entirely.

**Comment by tenzen-y** [comment]
> Hm, even though the feature itself is Alpha-level:
> 
> https://github.com/kubernetes-sigs/kueue/blob/38cedb172e42cbbeb8c12225baab827583db6c3b/pkg/features/kube_features.go#L40
> 
> ?
> I would prefer to deprecate it and drop entirely.

Oh, I see. I though this is under beta stage due to: https://github.com/kubernetes-sigs/kueue/blob/f2cba29c80349181773183bc053a0510ea399a5e/keps/168-pending-workloads-visibility/kep.yaml#L20

However, I think that we can not change APIs without backward compatibility since the ClusterQueue API is beta.

**Comment by mimowo** [comment]
Can we just keep dummy API and remove the code to support it, is there any procedure to remove beta apis?

**Comment by tenzen-y** [comment]
> Can we just keep dummy API and remove the code to support it

I'm not sure that it follows the Kubernetes deprecation policy. Let us know what we should do in this case.

> is there any procedure to remove beta apis?

You mean that introducing a new API version, v1beta2 or v1?

**Comment by mimowo** [comment]
> You mean that introducing a new API version, v1beta2 or v1?

I meant to remove an API field, possibly going to v1beta2 without the fields.

**Comment by tenzen-y** [comment]
> I meant to remove an API field

This way has breaking backward compatibility... So I think that we can not take this way.

> possibly going to v1beta2 without the fields.

If so, we probably need to provide conversion webhooks.

**Comment by alculquicondor** [comment]
Yes, we should remove it once we are ready to go to v1beta2 or v1.

Let's close this for now.

/close
