### ISSUE TITLE
Fleky multikueue E2E tests

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/kueue#1663]
**What happened**:

The below error happened:

```shell
{Timed out after 30.000s.
Expected
    <nil>: nil
to be a NotFound error failed [FAILED] Timed out after 30.000s.
Expected
    <nil>: nil
to be a NotFound error
In [BeforeSuite] at: /home/prow/go/src/sigs.k8s.io/kueue/test/util/e2e.go:74 @ 01/29/24 10:28:36.861
}
```

**What you expected to happen**:

No errors happened.

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/1662/pull-kueue-test-e2e-main-1-29/1751913992147701760

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tenzen-y** [comment]
cc: @trasc

**Comment by trasc** [comment]
/close

This happened because out of the two replicas of kueue-controller-manager the one that is not the leader finished seting up the certificates and is able to perform the webhook actions (including adding RF finalizers), but the leader is still waiting for the certificate generation hence is unable to remove the RF finalizers.

However the way we wait for kueue to be ready has changed in #1674
