### ISSUE TITLE
[MultiKueue] Default managedBy for ClusterQueues configured to use MultiKueue AC

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#2022]
**What would you like to be added**:

Add the `managedBy` field if the JobSet is submitted to a ClusterQueue with MultiKueue AC.

**Why is this needed**:

Usability. The users should know as little about MK as possible, only admins. Once the system is setup by an admin the user does not need to know if this is MK or not. 

It will allow for smooth transition from single cluster to multiple cluster environments.

**Proposed approach**

The proposed solution is to use the `jobset_webhook` which would have access to the configuration of ClusterQueues via cache.

**Comment by alculquicondor** [comment]
I guess either the cache or the client (which is also cached). Whichever is less cumbersome.

There might be race conditions in either case, so that should not be a consideration when choosing between one or the other.

**Comment by trasc** [comment]
One problem that I see with this is that the `managedBy` field of the JobSet should be immutable (it looks like it's not the case now but I see this more as a bug on their side), and the workload queue of queue's admission checks are not. And we end up enforcing the state of the queues at the time the JobSet is created. 

What it might be more problematic, down the line is: 

- If multikueue is "added"  to the JobSet (added to the jobset's queue, or it's queue changes) the multikueue controller will reject it. (maybe not a huge problem)

- If multikueue is "removed"  from the JobSet  (from the jobset's queue, or it's queue changes )  when the JobSet will be admitted , since it's main controller will continue to ignore it, no progress will be done and the quota will remain reserved.

In case the `managedBy` mutability for JobSets is a feature , not  a bug,  then we can try to "flip" it from multikueue when ever it's the case.

**Comment by mimowo** [comment]
> In case the managedBy mutability for JobSets is a feature , not a bug, then we can try to "flip" it from multikueue when ever it's the case.

It should be immutable. We want consistency with Batch Job, where this was discussed at length.

**Comment by mimowo** [comment]
> What it might be more problematic, down the line is:

Yes, we are aware of race conditions like this, but the assumption is that ClusterQueue configurations are rare, once the system is setup.

That being said, the more helpful we can be in that situations the better. For example, maybe we could detect situations like these and evict the workloads, and mark as inactive.

**Comment by mimowo** [comment]
@vladikkuzn I think it would be good to follow up with a docs update. I think we can drop [this](https://github.com/kubernetes-sigs/kueue/blob/main/site/content/en/docs/tasks/run/jobsets.md#multikueue-environment) example. A short note, that the webhook updates the field should be enough.

**Comment by mimowo** [comment]
> @mimowo Is it better to do it in separate PR or in the same?

Either way would work for me. Maybe separate is slightly preferred.
