### ISSUE TITLE
Enable randomization in the queuing strategy

### ISSUE THREAD

**Issue by shaowei-su** [kubernetes-sigs/kueue#2297]
**What would you like to be added**:
Aside from `StrictFIFO` and `BestEffortFIFO `, allow randomized admission of queued workloads.

**Why is this needed**:
Today, we encourage users to submit as many workloads as possible to saturate the queue resources. However, this could lead to imbalanced admission of workloads based on FIFO for preemptible workloads.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [x] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by mimowo** [comment]
> Today, we encourage users to submit as many workloads as possible to saturate the queue resources. However, this could lead to imbalanced admission of workloads based on FIFO for preemptible workloads.

This is interesting, I would like to explore your setup to better understand the expectations. 

Do you mean that userA is faster to send the jobs than userB and they block the queue of userB for a prolonged time? If so, is it because userA and userB are in different time-zones? 

Resolving this type of imbalances is one of the objectives of the [Fair Sharing](https://github.com/kubernetes-sigs/kueue/tree/main/keps/1714-fair-sharing) - it will be released in 0.7, we are yet going to add some user-facing docs.

I would also like to know if you have generally short- or long-running jobs? Do you use same priority for all of them?

**Comment by shaowei-su** [comment]
> Do you mean that userA is faster to send the jobs than userB and they block the queue of userB for a prolonged time? If so, is it because userA and userB are in different time-zones?

Yes, userA could submit all his jobs all at once to the preemptible queues prior to userB; it's not necessarily time zone based issue, since a lot of the jobs are adhoc runs.

> I would also like to know if you have generally short- or long-running jobs? Do you use same priority for all of them?
Jobs tend to be long running ~ 10 hr, and currently we set the same priority for preemptible jobs.

Thanks @mimowo , could you point me to the PRs for this feature? I can test it out on our end as well.

**Comment by mimowo** [comment]
> Thanks @mimowo , could you point me to the PRs for this feature? I can test it out on our end as well.

I think a good entry point might be the API PR: https://github.com/kubernetes-sigs/kueue/pull/2070.
AFAIK @alculquicondor is working on some docs for 0.7.

**Comment by alculquicondor** [comment]
Fair sharing is documented here https://kueue.sigs.k8s.io/docs/concepts/preemption/#fair-sharing

I suppose that, with that, this feature request is no longer needed.

Please reopen with more details if you disagree.

/close
