### ISSUE TITLE
Flaky Performance Test: checker_test

### ISSUE THREAD

**Issue by IrvingMg** [kubernetes-sigs/kueue#2708]
**What happened**:
Flaky test for `test/performance/scheduler/checker TestScalability`.

```
=== Failed
=== FAIL: test/performance/scheduler/checker TestScalability/WorkloadClasses/large (0.00s)
    checker_test.go:117: Average wait for admission 11213ms is more then expected 11000ms
```

**What you expected to happen**:
Errors have never been seen.

**How to reproduce it (as minimally and precisely as possible)**:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kueue/2642/pull-kueue-test-scheduling-perf-main/1816858084459417600

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kueue version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by trasc** [comment]
This looks to be caused just by a high load in the test infra.

We can keep it open for tracking purposes.

**Comment by trasc** [comment]
I believe we can close it for now as:

1. the issue was no longer observed
2. we have the retry mechanism: https://github.com/kubernetes-sigs/kueue/pull/3020 , able to retry the test and ignore infra cased flakes (eg. https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kueue-test-scheduling-perf-main/1852546889136738304)
3. the board is clean for 2 months: https://testgrid.k8s.io/sig-scheduling#periodic-kueue-test-scheduling-perf-main

/close
