### ISSUE TITLE
Easy way to figure out other workloads that are pending / admitted

### ISSUE THREAD

**Issue by samos123** [kubernetes-sigs/kueue#2833]
**What would you like to be added**: Easy way to figure out other workloads that are pending / admitted

**Why is this needed**: As a workload owner my job went into pending state because there are other workloads admitted and in pending state. I want to know the following things:
* what are the names of the other workloads in pending and admitted state
* who submitted the workload
* how much resources are taken by each of the workloads

The reason is that I want to get an understanding of when my job may run and notify the other workload owners if needed.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by trasc** [comment]
The easiest way to get a workload's position in the queue is to use [kueuectl list workload](https://kueue.sigs.k8s.io/docs/reference/kubectl-kueue/commands/kueuectl_list/kueuectl_list_workload/) which hase a `POSITION IN QUEUE` column.

For more details you can also check [Monitor pending Workloads](https://kueue.sigs.k8s.io/docs/tasks/manage/monitor_pending_workloads/) section.

**Comment by mimowo** [comment]
/close
Closing since the main use-case of:

> The reason is that I want to get an understanding of when my job may run

Is already addressed as explained in https://github.com/kubernetes-sigs/kueue/issues/2833#issuecomment-2287936324. 

> and notify the other workload owners if needed.

This part isn't done yet, but its importance isn't that clear yet. We can still open a dedicated issue or re-open this if this remains needed for some.

Also, it isn't clear what the other owners should do with that knowledge - if they run lower priority Jobs which should be stopped, then the right mechanism to do it is to use [workload priorities](https://kueue.sigs.k8s.io/docs/concepts/workload_priority_class/). Then, Kueue will automatically preempt the lower priority workloads.
