### ISSUE TITLE
[MultiKueue] Promote MultiKueue API and feature gate to Beta

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#3095]
**What would you like to be added**:

Promote the MultiKueue API to Beta.

**Why is this needed**:

For the ease of use. 

The feature was first introduced in 0.6, and since then a bunch of issues have been fixed.

**Completion requirements**:

Issues I would like to get addressed before graduating (except from other graduation criteria mentioned in KEP):
- https://github.com/kubernetes-sigs/kueue/issues/3099
- https://github.com/kubernetes-sigs/kueue/issues/3094

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by tenzen-y** [comment]
@mimowo @trasc Could we finalize https://github.com/kubernetes-sigs/kueue/pull/2458 before we graduate MK?
I am suspecting that the new functional requirements will be found by #2458.

**Comment by mimowo** [comment]
Thanks for the comment, I was thinking about it, but I think we don't need to block on it, here is the couple of thoughts I have:
- it is very unlikely we will be able to finalize https://github.com/kubernetes-sigs/kueue/pull/2458 before end of November, given the load of other workstreams. The KEP proved to be challenging, and we need a proper design for it, which I think includes decoupling Job handling and ACs. 
- supporting external Jobs may will likely require new APIs, but I believe we can grow it later step by step, nothing in the current [API](https://github.com/kubernetes-sigs/kueue/blob/main/apis/kueue/v1alpha1/multikueue_types.go) seems would be blocking the support
- in the past we supported built-in Jobs in Kueue (initially just batch Job) as Beta API, and only later we added Job framwork and expanded and support external Jobs. I believe we can repeat the pattern here, while already in Beta.
- we are already getting user feedback that the current API is useful for JobSet, but the setup still requires many steps

**Comment by tenzen-y** [comment]
I discussed this graduation with @mimowo offline.
During the discussion, we agreed that external Job support would take a long time since https://github.com/kubernetes-sigs/kueue/pull/2458 has not been finalized and is pending status.

Additionally, I guess that this graduation would be useful for collecting feedback from users, and we can reflect the feedback to the external Job support. Based on user feedback, we will prepare the second beta version to support additional features and external Jobs.

Anyway, I agree with this beta graduation, but for the GA graduation, I would like to wait for external Job support.

**Comment by mimowo** [comment]
/close 
The remaining work is tracked in separate issue https://github.com/kubernetes-sigs/kueue/issues/3094
