### ISSUE TITLE
Use ResourceFlavorReference instead of string consistently

### ISSUE THREAD

**Issue by mimowo** [kubernetes-sigs/kueue#3491]
/kind cleanup

**What would you like to be cleaned**:

To use ResourceFlavorReference consistently, and only cast to string when absolutly needed

**Why is this needed**:

For example here: 
- flavor is casted ResourceFlavorReference -> string [here](https://github.com/kubernetes-sigs/kueue/blob/0f54466b991a7d198eeca306dc75f2aee518c482/pkg/controller/core/resourceflavor_controller.go#L242C22-L242C46)
- then down in the invocation stack it is casted back from string to ResourceFlavorReference: [here](https://github.com/kubernetes-sigs/kueue/blob/0f54466b991a7d198eeca306dc75f2aee518c482/pkg/cache/clusterqueue.go#L604C13-L604C36)

**Comment by shubhamch71** [comment]
Hi @mimowo I understand the goal is to consistently use ResourceFlavorReference type instead of string throughout the codebase, particularly in ClusterQueuesUsingFlavor() and related methods, only casting to string when absolutely necessary (like in NamespacedName). Could you help clarify the specific scenarios where casting to string would still be necessary apart from NamespacedName ?

**Comment by mbobrovskyi** [comment]
@shubhamch71 We need to use the `TopologyReference` type instead of string here: 
https://github.com/kubernetes-sigs/kueue/blob/0f54466b991a7d198eeca306dc75f2aee518c482/apis/kueue/v1beta1/resourceflavor_types.go#L97

Like here: 
https://github.com/kubernetes-sigs/kueue/blob/0f54466b991a7d198eeca306dc75f2aee518c482/apis/kueue/v1beta1/clusterqueue_types.go#L340-L341

This is an example how to initialize reference type:
https://github.com/kubernetes-sigs/kueue/blob/0f54466b991a7d198eeca306dc75f2aee518c482/apis/kueue/v1beta1/clusterqueue_types.go#L259-L262

**Comment by mimowo** [comment]
> the goal is to consistently use ResourceFlavorReference type instead of string throughout the codebase

yes

>  Could you help clarify the specific scenarios where casting to string would still be necessary apart from NamespacedName ?

AFAIK only when passing to NamespacedName, but I might be missing some place, it is part of the task to figure out all such places.

>  Also anything you can suggest to get started with this issue?

I think you are on the right track.

**Comment by kaisoz** [comment]
/assign 

@shubhamch71 I've assigned this one to myself because it's still free and you didn't add any update in some time. However, if you already started with it please let me know.

**Comment by shubhamch71** [comment]
@kaisoz Thanks for picking this up! I apologize for the delay on my end—I’ve been caught up with work and won’t be able to make further progress on it. Feel free to go ahead and take it forward.

**Comment by kaisoz** [comment]
@shubhamch71 No worries! I'll work on it, thanks for the response 😊
