### ISSUE TITLE
TAS: Optimize Workload object size by listing only hostname values in `.status.TopologyAssignment` field

### ISSUE THREAD

**Issue by PBundyra** [kubernetes-sigs/kueue#3671]
**What would you like to be added**:
Optimization to list only hostname values in TopologyAssignment if a user defines `kubernetes.io/hostname` in `Topology` object

**Why is this needed**:
To optimize Workload object size. Currently etcd object size is limited to 1,5MB and on large scale this can be a blocker for us to support big hero workloads

**Comment by mimowo** [comment]
cc @tenzen-y the reason is that if user specifies the `kubernetes.io/hostname` as the lowest level, then we don't need to pass the entire list of values in the `TopologyAssignment.domain[].values`, because the last value already identifies the node in the cluster. So, having just this in the nodeSelector for the pod is enough. In case "subblock" or "block" being the lowest level we still need to pass the entire path, because they could not be unique in the cluster.
