### ISSUE TITLE
☂️ Requirements for v0.4

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/kueue#636]
Targeting end of June

```[tasklist]
### Committed
- [ ] #510 
- [ ] #599 
- [ ] #610
- [ ] #612
- [ ] https://github.com/kubernetes-sigs/kueue/issues/534
- [ ] https://github.com/kubernetes-sigs/kueue/issues/738
```

```[tasklist]
### Nice to have (will not block the release)
- [ ] #78 
- [ ] #297
- [ ] #666
- [ ] #420
```

**Comment by alculquicondor** [comment]
cc @denkensk @ahg-g @mwielgus @kerthcet @tenzen-y

**Comment by ahg-g** [comment]
are the candidates listed in some rough priority?

**Comment by kerthcet** [comment]
Thanks for bringing this in! @alculquicondor 🎉

One concern is about the release cycle. This is a long term before we release v0.4.0, hope we can release minor versions regularly, users can experiment with the newest features randomly rather than building with master branch.  We haven't released any versions since August last year, I think it's not a good signal. I recalled we talked about this before but couldn't find the records.

**Comment by kerthcet** [comment]
I will vote for them as they're the shortcomings Kueue has
- https://github.com/kubernetes-sigs/kueue/issues/599
- https://github.com/kubernetes-sigs/kueue/issues/534
- https://github.com/kubernetes-sigs/kueue/issues/510
- https://github.com/kubernetes-sigs/kueue/issues/78

Also good to have:
- https://github.com/kubernetes-sigs/kueue/issues/610
- https://github.com/kubernetes-sigs/kueue/issues/582
- https://github.com/kubernetes-sigs/kueue/issues/77
- https://github.com/kubernetes-sigs/kueue/issues/420

**Comment by mwielgus** [comment]
After some chat with @alculquicondor we agreed to aim at 2-3 month release cycle. The project is still young and more frequent, narrow-scoped releases will probably both work better and look better. Thus the list can be roughly prioritised into three categories: 
* Will do - we will postpone release if the task is not finished.
* Maybe - we will try/strongly consider but will not postpone the release if the task is not finished.  
* For next releases - was considered for the release but most likely the task will not even be started.

Will do:
* #78 
* #510 
* #599 
* #610 

Maybe:
* #666 - the work has already been started - https://github.com/ray-project/kuberay/pull/926 but due to some refactoring the important dependency is on-hold
* #297 - depends on https://github.com/kubeflow/common/pull/196

For next releases:
* #77 - the needed infrastructure will land 1.27 (https://github.com/kubernetes/kubernetes/pull/116161) and it will be a while before 1.27 is actually in use.
* #582 - nice optimisation but no explicit need at this moment. 
* #420 - not sure about proper UX, most likely won't fit anyway.
* #28 - won't fit, too big, no clear API/UX yet.
* #74 - 2 frameworks already in the pipeline, will wait for the next release(s).

**Comment by denkensk** [comment]
> The project is still young and more frequent, narrow-scoped releases will probably both work better and look better. 

By the way, can we collect the cases used by some companies in the production environment, which will encourage more people to use and participate in this project?

**Comment by alculquicondor** [comment]
I have updated the issue description. @kerthcet @denkensk anything else you would like to add?
I will also share this list in the next WG meeting and in kubecon.

**Comment by kerthcet** [comment]
LGTM.

**Comment by alculquicondor** [comment]
I meant to add #534 as well

**Comment by alculquicondor** [comment]
I added #738 to the committed list

**Comment by alculquicondor** [comment]
/close
with https://github.com/kubernetes-sigs/kueue/releases/tag/v0.4.0
